import './globals.css'
import { Inter } from 'next/font/google'
import SideBar from './SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen">
          <SideBar />
          <div className="flex-1 min-w-[400px] overflow-none">
            {children}  
          </div>
        </div>
      </body>
    </html>
  )
}
